# Generated by Django 3.1.1 on 2020-12-04 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='image',
            field=models.ImageField(default='default2.jpg', upload_to='content_pics'),
        ),
    ]
