# Generated by Django 3.1.1 on 2020-12-07 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0002_article_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='image',
            field=models.ImageField(default='default2.jpg', upload_to='article_pics'),
        ),
    ]
