# Generated by Django 3.1.1 on 2021-05-16 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0005_auto_20201210_1512'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='image',
            field=models.ImageField(default='default2.jpeg', upload_to='article_pics'),
        ),
    ]
